//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGySoft.Drawing.ImagingTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOSLanguage {
            get {
                return ((bool)(this["UseOSLanguage"]));
            }
            set {
                this["UseOSLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Default)")]
        public global::System.Globalization.CultureInfo DisplayLanguage {
            get {
                return ((global::System.Globalization.CultureInfo)(this["DisplayLanguage"]));
            }
            set {
                this["DisplayLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResXResourcesCustomPath {
            get {
                return ((string)(this["ResXResourcesCustomPath"]));
            }
            set {
                this["ResXResourcesCustomPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmoothZoomingDefault {
            get {
                return ((bool)(this["SmoothZoomingDefault"]));
            }
            set {
                this["SmoothZoomingDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SmoothZoomingMetafile {
            get {
                return ((bool)(this["SmoothZoomingMetafile"]));
            }
            set {
                this["SmoothZoomingMetafile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmoothZoomingMultiResIcon {
            get {
                return ((bool)(this["SmoothZoomingMultiResIcon"]));
            }
            set {
                this["SmoothZoomingMultiResIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SmoothZoomingBitmap {
            get {
                return ((bool)(this["SmoothZoomingBitmap"]));
            }
            set {
                this["SmoothZoomingBitmap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoZoomMultiResIcon {
            get {
                return ((bool)(this["AutoZoomMultiResIcon"]));
            }
            set {
                this["AutoZoomMultiResIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoZoomBitmap {
            get {
                return ((bool)(this["AutoZoomBitmap"]));
            }
            set {
                this["AutoZoomBitmap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoShrinkLargeBitmap {
            get {
                return ((bool)(this["AutoShrinkLargeBitmap"]));
            }
            set {
                this["AutoShrinkLargeBitmap"] = value;
            }
        }
    }
}
